In [2]:
import numpy as np

In [3]:
#1
a = np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
#2
b = np.arange(10, 50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [20]:
#3
c = np.random.randint(-1, 1, 10)
print(c)
np.nonzero(c)

[-1 -1  0  0  0  0  0 -1 -1 -1]


(array([0, 1, 7, 8, 9]),)

In [38]:
#4
d = np.arange(0, 9).reshape(3, 3)
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
#5
e = np.array([0, 1])
np.tile(e, (8, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [22]:
#6
f = np.random.rand(10)
print(f)
f[f.argmin()] = 0
print(f)

[0.81208773 0.18205634 0.06040106 0.44467769 0.58258602 0.5925116
 0.88215228 0.4360143  0.21154589 0.55086625]
[0.81208773 0.18205634 0.         0.44467769 0.58258602 0.5925116
 0.88215228 0.4360143  0.21154589 0.55086625]


In [26]:
#7
j = np.random.randint(0, 10, 10)
print(j)
np.bincount(j).argmax()

[3 1 5 9 7 8 4 0 3 4]


3

In [39]:
#8
h = np.random.randint(0, 5, 9).reshape(3, 3)
print(h)
mean = np.mean(h, axis=1).reshape(3, 1)
h - mean

[[2 2 4]
 [1 0 4]
 [3 4 4]]


array([[-0.66666667, -0.66666667,  1.33333333],
       [-0.66666667, -1.66666667,  2.33333333],
       [-0.66666667,  0.33333333,  0.33333333]])

In [42]:
#9
i = np.random.randint(0, 5, 25).reshape(5, 5)
print(i)
i[[2, 4]] = i[[4, 2]]
print(i)


[[2 4 1 3 0]
 [3 3 2 1 0]
 [1 3 0 1 3]
 [2 0 4 0 2]
 [1 1 1 0 4]]
[[2 4 1 3 0]
 [3 3 2 1 0]
 [1 1 1 0 4]
 [2 0 4 0 2]
 [1 3 0 1 3]]


In [49]:
#10
f = np.random.randint(0, 10, 10)
print(f)
np.unique(f)[3:]

[4 6 3 6 1 2 9 9 2 6]


array([4, 6, 9])

In [54]:
#11
#g = np.array([np.arange(1, 6)] * 5)

g = np.arange(1, 6)
np.tile(g, (5, 1))

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [61]:
#12
k = np.random.randint(-9, 10, 16).reshape(4, 4)
l = np.random.randint(-9, 10, 16).reshape(4, 4)
mult = np.dot(k, l)
print(mult)
print(mult[np.diag_indices(4)])
print(np.fliplr(mult)[np.diag_indices(4)])

[[  1  63 -64  47]
 [-16 -39 -59  49]
 [-12  16 -68  56]
 [ 31  -9 -10  71]]
[  1 -39 -68  71]
[ 47 -59  16  31]
